site: microgeni

email: daniel@microgeni.se
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://microgeni.se" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  danielbenjaminsson
linkedin_username: daniel-benjaminsson-05431074


#url:
#baseurl:

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blogg/:slug
  projects:
    output: true
    permalink: /project/:slug
  nyheter:
    output: true
    permalink: /nyheter/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6   # how many blog post on each page
paginate_path: "/blogg/page:num/"
